services:
  web-api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: web-api
    build:
      context: .
      dockerfile: src/Web.Api/Dockerfile
    ports:
      - 80:8080

  postgres:
    image: postgres:latest
    container_name: fltracker.db
    environment:
      - POSTGRES_DB=fltracker
      - POSTGRES_USER=fltrackeradmin
      - POSTGRES_PASSWORD=fltrackeradmin
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80

volumes:
  postgres: